import jsPDF from 'jspdf';

export function downloadTextAsPdf(title, text) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  doc.setFont('helvetica');
  doc.setFontSize(16);
  doc.text(title, 40, 60);
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text('Generated by Sentinel One', 40, 80);
  doc.setFontSize(12);
  doc.setTextColor(30);
  doc.setFont('courier');
  const lines = doc.splitTextToSize(text, 500);
  doc.text(lines, 40, 110);
  doc.save(title.replace(/[^a-z0-9]+/gi, '_').toLowerCase() + '.pdf');
}
